apiVersion: v1
kind: Secret
metadata:
  name: massa-secrets
  namespace: massa
type: Opaque
# Замените значения на base64-encoded строки
# echo -n "your_password" | base64
data:
  PG_USER: cG9zdGdyZXM=  # postgres
  PG_PASSWORD: cG9zdGdyZXM=  # postgres (замените на свой пароль!)
